import type { ProjectStatus, TaskStatus } from "@/lib/constants";

const STATUS_COLORS: Record<ProjectStatus, string> = {
  "creative-scoping": "bg-neutral-100 text-neutral-700",
  "script-lock": "bg-sky-100 text-sky-800",
  "production-logistics": "bg-amber-100 text-amber-800",
  production: "bg-blue-100 text-blue-800",
  "post-production": "bg-purple-100 text-purple-800",
  delivered: "bg-green-100 text-green-800",
  archived: "bg-neutral-100 text-neutral-500",
};

export function ProjectStatusBadge({ status }: { status: string }) {
  const cls = STATUS_COLORS[status as ProjectStatus] ?? "bg-neutral-100 text-neutral-700";
  return (
    <span className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-medium ${cls}`}>
      {status}
    </span>
  );
}

const TASK_STATUS_COLORS: Record<TaskStatus, string> = {
  not_started: "bg-neutral-100 text-neutral-600",
  in_progress: "bg-blue-100 text-blue-800",
  ready_for_review: "bg-amber-100 text-amber-800",
  complete: "bg-green-100 text-green-800",
  n_a: "bg-neutral-50 text-neutral-400",
};

export function TaskStatusBadge({ status }: { status: string }) {
  const cls = TASK_STATUS_COLORS[status as TaskStatus] ?? "bg-neutral-100 text-neutral-600";
  return (
    <span className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${cls}`}>
      {status.replace(/_/g, " ")}
    </span>
  );
}

export function SuggestionBadge() {
  return (
    <span
      title="Generated by the template/AI engine — review before treating as final."
      className="inline-flex items-center gap-1 rounded-full bg-violet-100 px-2 py-0.5 text-xs font-medium text-violet-800"
    >
      Suggestion
    </span>
  );
}

export function ProgressBar({ value }: { value: number }) {
  const pct = Math.max(0, Math.min(100, Math.round(value * 100)));
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-neutral-200">
      <div
        className="h-full rounded-full bg-neutral-900 transition-all"
        style={{ width: `${pct}%` }}
      />
    </div>
  );
}
